name: bisq-desktop
base: core18
version: git
summary: Peer-to-peer exchange to trade various curriencies for bitcoin
description: |
  Cross-platform desktop application that allows users to trade national currency (dollars, euros, etc) for bitcoin without relying on centralized exchanges
confinement: strict
grade: stable
icon: snap/local/icon.png

apps:
  bisq-desktop:
    extensions:
      - gnome-3-28
    command: bisq-desktop
    plugs:
      - network
      - network-bind
      - desktop
      - desktop-legacy
      - x11
      - wayland
      - home
      - gsettings
      - camera
      - opengl
    desktop: usr/share/applications/bisq.desktop
    environment:
      JAVA_HOME: "$SNAP/usr/lib/jvm/java-11-openjdk-amd64"
      JAVA_TOOL_OPTIONS: "-Duser.home=$SNAP_USER_COMMON -Dprism.debugfonts=true"

parts:
  bisq:
    plugin: gradle
    override-build: |
      ./gradlew build -x test

      # Install executable and jars
      install -d "${SNAPCRAFT_PART_INSTALL}/opt/bisq"
      cp desktop/build/app/bin/bisq-desktop "${SNAPCRAFT_PART_INSTALL}/usr/bin"
      cp -r desktop/build/app/lib/* "${SNAPCRAFT_PART_INSTALL}/usr/lib"

      # Install desktop launcher icon
      install -Dm644 desktop/package/linux/icon.png "${SNAPCRAFT_PART_INSTALL}/usr/share/pixmaps/bisq.png"

    source: .
    build-packages:
      - openjdk-11-jdk
    stage-packages:
      - libgl1
      - libglx0
      - libxtst6
      - libxxf86vm1
      - libv4l-0
      - libasound2
      - freeglut3
      - libgtk2.0-0
      - libavcodec57
      - libavformat57
      - openjfx

  # Install desktop launcher
  launchers:
    plugin: dump
    source: snap/local
    organize:
      'bisq.desktop': usr/share/applications/bisq.desktop
